MAX_RGB_VALUE = 255
INDIVIDUAL_CHARACTER_HEIGHT = 18
INDIVIDUAL_CHARACTER_WIDTH = 8
IMAGE_SCALOR = 0.4
chars = "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^'. "
simpler_chars = "#@Wo-/\\ "

RED_WEIGHT = 0.299
GREEN_WEIGHT = 0.587
BLUE_WEIGHT = 0.114
